---
version: '0.2'

import: []

ignorePaths: []
dictionaryDefinitions: []

dictionaries:
  - en_US
  - softwareTerms
  - bash

words: []

ignoreWords:
  - atuin
  - atuinsh
  - blesh
  - binutils
  - bufread
  - clippy
  - dysk
  - gitui
  - reqwest
  - rustdoc
  - rustls
  - sharkdp
  - softprops
  - trixie
  - yazi
  - zstd
